version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ci3_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - ci3_network

  webserver:
    image: nginx:stable-alpine
    container_name: ci3_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - ci3_network

  db:
    image: mysql:8.0
    container_name: ci3_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ci3
      MYSQL_USER: ci3user
      MYSQL_PASSWORD: ci3pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ci3_network

networks:
  ci3_network:

volumes:
  db_data:
